#!/bin/bash
# start_session.sh — Start a dataset recording session with auto-generated manifest.
#
# Usage:
#   ./start_session.sh <robot_name> <scenario>
#   ./start_session.sh agv1 corridor_loop
#
# What it does:
#   1. Validates that ROS is running and all required topics are publishing
#   2. Generates a session_manifest.yaml before recording starts
#   3. Launches roslaunch agv_bringup logging.launch
#   4. On Ctrl+C, finalises the manifest with duration and bag size
#
# Run this ON THE ROBOT, not the Mac.

set -e

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
ROBOT_NAME="${1:-agv_unknown}"
SCENARIO="${2:-unknown_scenario}"
DATESTAMP=$(date +%Y%m%d_%H%M%S)
SESSION_ID="${ROBOT_NAME}_${SCENARIO}_${DATESTAMP}"
BAG_DIR="${HOME}/agv_data"
BAG_FILE="${BAG_DIR}/${SESSION_ID}.bag"
MANIFEST_FILE="${BAG_DIR}/${SESSION_ID}_manifest.yaml"

mkdir -p "${BAG_DIR}"

# ---------------------------------------------------------------------------
# Source ROS
# ---------------------------------------------------------------------------
source /opt/ros/melodic/setup.bash
source "${HOME}/slam_project/myagv_ros/devel/setup.bash"
source "${HOME}/slam_project/agv_ws/devel/setup.bash"

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
echo "=== Pre-flight checks ==="

# Check roscore is running
if ! rostopic list > /dev/null 2>&1; then
    echo "ERROR: ROS master not running. Start bringup first or this script will launch it."
fi

# Check required topics are publishing (best-effort, don't block)
REQUIRED_TOPICS="/scan /odom /camera/color/image_raw /camera/aligned_depth_to_color/image_raw /camera/imu"
ALL_OK=true
for topic in $REQUIRED_TOPICS; do
    if rostopic hz "$topic" --window 10 2>/dev/null | grep -q "average rate"; then
        echo "  [✓] $topic publishing"
    else
        # Try simpler check
        if timeout 3 rostopic echo "$topic" -n 1 > /dev/null 2>&1; then
            echo "  [✓] $topic publishing"
        else
            echo "  [!] $topic not detected — may not be running yet"
            ALL_OK=false
        fi
    fi
done

if [ "$ALL_OK" = false ]; then
    echo ""
    echo "WARNING: Some topics not detected. Starting logging anyway."
    echo "Run validate_bag.py after recording to check data quality."
    echo ""
fi

# ---------------------------------------------------------------------------
# Write initial manifest
# ---------------------------------------------------------------------------
ROS_DISTRO_VAL=$(echo "${ROS_DISTRO:-melodic}")
CALIB_DIR="${HOME}/slam_project/agv_ws/src/agv_bringup/calibration"
if [ -d "$CALIB_DIR" ]; then
    CALIB_HASH=$(find "$CALIB_DIR" -type f | sort | xargs sha256sum 2>/dev/null | sha256sum | cut -d' ' -f1)
else
    CALIB_HASH="unavailable"
fi

cat > "${MANIFEST_FILE}" << EOF
# Session manifest — auto-generated by start_session.sh
session_id: ${SESSION_ID}
robot_id: ${ROBOT_NAME}
scenario: ${SCENARIO}
date: $(date +%Y-%m-%d)
time_start: $(date +%H:%M:%S)
time_end: ~
operator: $(whoami)
ros_distro: ${ROS_DISTRO_VAL}
bag_file: ${SESSION_ID}.bag
bag_size_mb: ~
duration_sec: ~
calibration_hash: "sha256:${CALIB_HASH}"
notes: ""
usb_mode_note: "D435i connected via USB 3 cable to USB 2 port — validate sync quality with validate_bag.py"
EOF

echo ""
echo "=== Session: ${SESSION_ID} ==="
echo "Bag:      ${BAG_FILE}"
echo "Manifest: ${MANIFEST_FILE}"
echo ""
echo "Press Ctrl+C to stop recording."
echo ""

# ---------------------------------------------------------------------------
# Record start time for duration calculation
# ---------------------------------------------------------------------------
START_EPOCH=$(date +%s)

# ---------------------------------------------------------------------------
# Launch logging (trap Ctrl+C to finalise manifest)
# ---------------------------------------------------------------------------
finalise_manifest() {
    echo ""
    echo "=== Finalising manifest ==="
    END_EPOCH=$(date +%s)
    DURATION=$((END_EPOCH - START_EPOCH))

    if [ -f "${BAG_FILE}" ]; then
        BAG_SIZE_MB=$(du -m "${BAG_FILE}" 2>/dev/null | cut -f1)
    else
        # rosbag appends .bag automatically but also sometimes names it differently
        ACTUAL_BAG=$(ls "${BAG_DIR}/${SESSION_ID}"*.bag 2>/dev/null | head -1)
        BAG_SIZE_MB=$(du -m "${ACTUAL_BAG}" 2>/dev/null | cut -f1 || echo "~")
    fi

    # Update manifest with final values
    sed -i "s/time_end: ~/time_end: $(date +%H:%M:%S)/" "${MANIFEST_FILE}"
    sed -i "s/bag_size_mb: ~/bag_size_mb: ${BAG_SIZE_MB:-unknown}/" "${MANIFEST_FILE}"
    sed -i "s/duration_sec: ~/duration_sec: ${DURATION}/" "${MANIFEST_FILE}"

    echo "Duration: ${DURATION}s"
    echo "Bag size: ${BAG_SIZE_MB:-unknown} MB"
    echo "Manifest written: ${MANIFEST_FILE}"
    echo ""
    echo "Run quality check:"
    echo "  python3 scripts/logging/validate_bag.py ${BAG_DIR}/${SESSION_ID}.bag"
}

trap finalise_manifest EXIT

# Export env vars for logging.launch
export ROBOT_NAME="$ROBOT_NAME"
export SCENARIO="$SCENARIO"
export DATESTAMP="$DATESTAMP"

roslaunch agv_bringup logging.launch
